---

    - name: Disable UFW
      become: yes
      ufw:
        state: disabled

    - name: Enable UFW and deny all incoming
      become: yes
      ufw:
        default: deny
        state: enabled

    - name: Enable UFW and allow specific ports
      become: yes
      ufw:
        state: enabled
        rule: allow
        port: "{{ item }}"
      loop:
        - 22 
        - 80 
        - 443 

    - name: Reload UFW
      become: yes
      ufw:
        state: reloaded