---
- hosts: all
  user: root
  # vars: 
  #   username: root
  #   public_key: ~/.ssh/id_rsa.pub
  #   user: amirmohammad
  vars_files: 
    - ./vars/main.yaml
  roles:
    - upgrade_debian_packages
    - install_required_packages
    - create_user
    - ssh_only_auth
    - install_docker
    - install_nodejs