---
- hosts: all
  user: osboxes
  become_user: root
  become_method: sudo
  # vars: 
  #   username: root
  #   public_key: ~/.ssh/id_rsa.pub
  #   user: amirmohammad
  vars_files: 
    - ./vars/main.yaml
  roles:
    # - dns_configuration
    # - upgrade_debian_packages
    # - install_required_packages
    # - create_user
    # - ssh_only_auth
    # - install_docker
    # - install_python3_packages
    # - set_timezone
    # - ufw_tasks
    - elk


    
    # - install_nodejs