---
  - name: disable password auth 
    become: true
    lineinfile :
      dest: /etc/ssh/sshd_config
      regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
      state: present
    notify: restart ssh