---
  - name: Update all packages
    become: yes
    apt:
      update_cache: yes
      force_apt_get: yes
      update_cache_retries: yes

  # - name: Update packages to latest version
  #   become: yes
  #   apt: 
  #     upgrade: dist
  #     force_apt_get: yes

  # - name: Check if a reboot is needed
  #   become: yes
  #   stat: 
  #     path: /var/run/reboot-required 
  #     get_md5: no
  #   register: reboot_required
    
  # - name: Reboot the server
  #   become: yes
  #   reboot: 
  #     msg: "Reboot by Ansible due to updates"
  #     connect_timeout: 5
  #     reboot_timeout: 300
  #     test_command: uptime
  #   when: reboot_required.stat.exists
