---
  - name: Update all packages
    apt:
      update_cache: yes
      force_apt_get: yes
      update_cache_retries: yes
      upgrade: safe

  - name: Update packages to latest version
    apt: 
      upgrade: dist
      force_apt_get: yes

  - name: Check if a reboot is needed
    stat: 
      path: /var/run/reboot-required 
      get_md5: no
    register: reboot_required
    
  - name: Reboot the server
    reboot: 
      msg: "Reboot by Ansible due to updates"
      connect_timeout: 5
      reboot_timeout: 300
      test_command: uptime
    when: reboot_required.stat.exists
