---
  - name: install required python packages
    pip:
      name:
        - virtualenv
        - pandas
        - matplotlib
        - seaborn
        - scikit-learn
        - numpy 
      state: present
